import { ZALGO_REGEX } from './constants';

export enum CensorRuleType {
	Swear,
	CopyPasta,
	Invite,
	Spam,
	Zalgo,
}

const { Swear, CopyPasta, Invite, Spam, Zalgo } = CensorRuleType;

export const CENSOR_RULES = [
	{ rule: ZALGO_REGEX.toString(), type: Zalgo, enabled: true },
	{ rule: '\\b(horny)', type: Swear, enabled: true },
	{ rule: '\\b(boobs?)', type: Swear, enabled: true },
	{
		rule: '\\b(anal(?!(ysis|y(s|z)(e|ing)|ytic(al|s)?|ogy)))',
		type: Swear,
		enabled: true,
	},
	{
		rule: '\\b(a\\.?(ss|\\$\\$)+(es)?(?![a-z]))',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(sl(u|e)t)', type: Swear, enabled: true },
	{ rule: '\\b(jerks)', type: Swear, enabled: true },
	{ rule: '\\b(brainfuck)', type: Swear, enabled: true },
	{ rule: '\\b(d(i|1|1|!)?c!?k)', type: Swear, enabled: true },
	{
		rule: '\\b(s(e|3)x(?!(y|uality|ualities)))',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(bastard)', type: Swear, enabled: true },
	{ rule: '\\b(rape(ist)?)', type: Swear, enabled: true },
	{ rule: '\\b(douche)', type: Swear, enabled: true },
	{ rule: '\\b(yiff)', type: Swear, enabled: true },
	{ rule: '\\b(slag)', type: Swear, enabled: true },
	{ rule: '\\b(twat)', type: Swear, enabled: true },
	{ rule: '\\b(testicles?)', type: Swear, enabled: true },
	{ rule: '\\b(p\\.?ussy)', type: Swear, enabled: true },
	{ rule: '\\b(hentai)', type: Swear, enabled: true },
	{ rule: '\\b(virgin(ity)?)', type: Swear, enabled: true },
	{ rule: '\\b(paki)', type: Swear, enabled: true},
	{ rule: '\\b(milf)', type: Swear, enabled: true },
	{ rule: '\\b(sped)', type: Swear, enabled: true },
	{ rule: '\\b(brothel)', type: Swear, enabled: true },
	{ rule: '\\b(thot)', type: Swear, enabled: true },
	{
		rule:
			'\\b((n|/\\\\/)(1|i|!|e|3)(g|gg|bb|qq)(?!(otiat(e|ing|or|ion)|otiable|lect(able|ed)?|ative|le|erian?))(?!(h|at))(a|3r|er)?)',
		type: Swear,
		enabled: true,
	},
	{
		rule: '\\b(c(o|0)ck(?!roach|er spaniel|y)(head|sucker)?)',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(tit(ties|s))', type: Swear, enabled: true },
	{ rule: '(.)(?=([a-z\\.]){17})', type: Spam, enabled: false },
	{
		rule: '\\b(mine)?(f(\\.)?((uc|[uc]|vc)(k|q)|(uk|uc|\\.ck|(\\.|,)uck)))',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(wh?at (da|the) fawk)', type: Swear, enabled: true },
	{ rule: '\\b(intercourse)', type: Swear, enabled: true },
	{ rule: '\\b(cum)', type: Swear, enabled: true },
	{ rule: '\\b(anus)', type: Swear, enabled: true },
	{ rule: '\\b(dildo)', type: Swear, enabled: true },
	{
		rule: '\\b(reta ?r(d(?!ant)|te?d))',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(blowjob)', type: Swear, enabled: true },
	{ rule: '\\b(p(e|3)nn?is)', type: Swear, enabled: true },
	{ rule: '\\b(piss)', type: Swear, enabled: false },
	{ rule: '\\b(c(u)nt)', type: Swear, enabled: true },
	{ rule: '\\b(whore)', type: Swear, enabled: true },
	{ rule: '\\b(b(i|\\*)t?ch)', type: Swear, enabled: true },
	{ rule: '\\b(asshole)', type: Swear, enabled: true },
	{ rule: '\\b(prick)', type: Swear, enabled: true },
	{ rule: '\\b(fag(got)?)', type: Swear, enabled: true },
	{ rule: '\\b(vagina)', type: Swear, enabled: true },
	{ rule: '\\b(mibb(a|er))', type: Swear, enabled: true },
	{ rule: '\\b((hub)?p(o|0)rn(hub)?)', type: Swear, enabled: true },
	{ rule: '\\b(sperm)', type: Swear, enabled: true },
	{ rule: '\\b(aroused)', type: Swear, enabled: true },
	{ rule: '\\b(wanker)', type: Swear, enabled: true },
	{ rule: '\\b(gas( )?(the)?( )?jews)', type: Swear, enabled: true },
	{ rule: '\\b(hitler|nazi)', type: Swear, enabled: true },
	{ rule: '\\b(erection)', type: Swear, enabled: true },
	{ rule: '\\b(fisting)', type: Swear, enabled: true },
	{ rule: '\\b(motherfucker)', type: Swear, enabled: true },
	{ rule: '\\b(chode)', type: Swear, enabled: true },
	{
		rule: '\\b(masterbat(e|ion|or))',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(suicide)', type: Swear, enabled: true },
	{ rule: '\\b(wank)', type: Swear, enabled: true },
	{
		rule: '\\b(brazzerss?|youporn|spankbang|xvideos)',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(buttplug)', type: Swear, enabled: true },
	{ rule: '\\b(chingar)', type: Swear, enabled: true },
	{ rule: '\\b(marijuana|weed)', type: Swear, enabled: true },
	{ rule: '\\b(d(i|y)ke)', type: Swear, enabled: true },
	{ rule: '\\b(beaner)', type: Swear, enabled: true },
	{ rule: '\\b(cyka)', type: Swear, enabled: true },
	{ rule: '\\b(blyat)', type: Swear, enabled: true },
	{ rule: '\\b(merde)', type: Swear, enabled: true },
	{
		rule: '\\s(\\[[a-z0-9]{8,}\\])$',
		type: Spam,
		enabled: false,
	},
	{ rule: '\\b(ddos)', type: Swear, enabled: false },
	{ rule: '卍', type: Swear, enabled: true },
	{ rule: '\\b((?<!s)kys)', type: Swear, enabled: true },
	{ rule: '\\b(kcuf)', type: Swear, enabled: true },
	{ rule: '\\b((bull?|horse)shit)', type: Swear, enabled: true },
	{ rule: '\\b(kanker)', type: Swear, enabled: true },
	{ rule: '\\b(:middle_finger:)', type: Swear, enabled: true },
	{
		rule: '\\b((dip|dog)?s?(s|$|5)h(\\.|,)?(i|1|!)?1?(t|\\+))',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(naked)', type: Swear, enabled: false },
	{ rule: '\\b(cancer)', type: Swear, enabled: true },
	{ rule: '\\b(pp(?![a-z]))', type: Swear, enabled: true },
	{
		rule: '\\b(chupa mi polla|sut min pik)',
		type: Swear,
		enabled: true,
	},
	{
		rule: '[█゜▔゛▫■œ∑´®†¥¨ˆøπ¬˚∆˙©ƒ∂ßåΩ≈ç√∫˜µ]{8,}',
		type: Spam,
		enabled: true,
	},
	{ rule: '\\b(polidicks)', type: Swear, enabled: true },
	{ rule: '\\b(gayass)', type: Swear, enabled: true },
	{ rule: '\\b(dumbass)', type: Swear, enabled: true },
	{ rule: '\\b(p(a)?edo(file)?)', type: Swear, enabled: true },
	{
		type: Swear,
		enabled: true,
		rule: '\\b(LiquidBounce|MoonX)',
	},
	{
		rule:
			'\\b(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])',
		type: Swear,
		enabled: true,
	},
	{
		rule:
			'\\b(n( |\\\)?i( |\\\)?g( |\\\)?g( |\\\)?(e( |\\\)?r|a)|f( |\\.|,|\\*|_)?(u|ú)?( |\\.|,|\\*|_)?c( |\\.|,|\\*|_)?k|(?<!player\\\')s ?h ?i ?t|b ?i ?t ?c ?h ?(e ?)?s?(?!allenging)|(?<!s)k ?y ?s|d ?i ?c ?k)',
		type: Swear,
		enabled: true,
	},
	{ rule: '\\b(fk(?!dr)( off+)?)', type: Swear, enabled: true },
	{
		rule:
			'\\b((https?://)?(www.)?(discord.(gg|io|me|li)|discord(app)?.com/invite)/(?<invite>.+[a-z]))',
		type: Invite,
		enabled: true,
	},
	{
		rule:
			'\\b((https://)?(www.)?(.+\\.)?zoom.us/j/.+)',
			type: Swear,
			enabled: true,
	},
	{
		rule:
			'\\b((https://)?(www\\.)?tornadus.net/orange)',
			type: Swear,
			enabled: true,
	},
	{
		rule: '\\b(reallybadword)',
		type: CopyPasta,
		enabled: true,
	},
	{
		rule: '\\b(Copy And Paste (Him|Her))',
		type: CopyPasta,
		enabled: true,
	},
	{
		rule: '\\b(This is (memedog|memecat))',
		type: CopyPasta,
		enabled: true,
	},
	{
		rule: '\\b(Look out for (a|the) discord user)',
		type: CopyPasta,
		enabled: true,
	},
];
